BaoZhang2024/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url( r'backend/', include( 'backend.urls' ) ),
    url(r'^', include('mySite.urls')),
]

mySite/urls.py
#:coding:utf8
"""BaoZhang2024 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from views import home, realViews#不同app里的views包同名,是否会发生冲突

urlpatterns = [
    url(r'^mySite/(?P<articleType>\d)/$', realViews.index, name='mySiteIndex'),
    url(r'mySite/register.html', realViews.doRegisterForm, name='register'),
    url(r'mySite/login.html', realViews.doLogin, name='login'),
    url(r'mySite/getCheckcode', realViews.getValidateCodeImage),
    url(r'mySite/logout', realViews.doLogout, name='logout'),
    url(r'^(?P<surfix>\w+)\/date\/(?P<theDate>\d{4}-\d{2})\.html', home.theDateArticles),
    url(r'(?P<surfix>\w+)\/label\/(?P<label_id>\d)\.html', home.theLabelArticles),
    url(r'(?P<surfix>\w+)\/(?P<artilce_id>\d+)\.html', home.wholeArticle ),
    url(r'^userAttitleTheArticle/', home.userAttitleTheArticle),
    url(r'^readerCommentTheArticle/', home.readerCommentTheArticle),
    url(r'^uploadFiles.html', home.upLoadFiles),
    url( r'^(?P<surfix>\w+)\.html$', home.index ),
    url(r'^$', realViews.index),
]

repository/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


# Create your models here.

class users(models.Model):
    username = models.CharField(max_length=16)
    password = models.CharField(max_length=10)
    email    = models.EmailField(max_length=16)
    headPicture_path = models.CharField(max_length=128)
    class Meta:
        verbose_name_plural = 'User Table'
    def __str__(self):
        return self.username


class blogs(models.Model):
    title = models.CharField(max_length=32)
    summary = models.CharField(max_length=128)
    owner   = models.OneToOneField(to=users)
    surfix  = models.CharField(max_length=64, unique=True)

    themeChoices = [
        (0, "homeBlue"),
        (1, "homeRed"),
    ]
    theme   = models.IntegerField(choices=themeChoices)

    def __str__(self):
        return self.title

class reportTroubles(models.Model):
    uid = models.UUIDField(max_length=16)
    title = models.CharField(max_length=32)
    detail = models.CharField(max_length=256)
    reportPerson = models.ForeignKey(to=users, related_name="report_person")
    dealPerson   = models.ForeignKey(to=users, related_name="deal_person", null=True, blank=True)
    ctime        = models.DateTimeField()
    Dtime        = models.DateTimeField()

    statusTypes = [
        (0, "willDeal"),
        (1, "Dealing"),
        (2, "Dealed"),
    ]
    status      = models.IntegerField(choices=statusTypes)

class classifications(models.Model):
    className = models.CharField(max_length=16)
    owner     = models.ForeignKey(to=blogs)
    def __str__(self):
        return self.className

class articlesDetail(models.Model):
    content = models.TextField()

class articles(models.Model):
    title    = models.CharField(max_length=16)
    summary  = models.CharField(max_length=64)
    ownerBlog= models.ForeignKey(to=blogs)
    ctime    = models.DateTimeField()
    detail   = models.OneToOneField(to=articlesDetail)

    type_choices = [
        (0, "Python"),
        (1, "Linux"),
        (2, "OpenStack"),
        (3, "GoLang"),
    ]
    articleType    = models.IntegerField(choices=type_choices)
    classification = models.ForeignKey(to=classifications)
    favorCount     = models.IntegerField(default=0)
    opposeCount    = models.IntegerField(default=0)
    def __str__(self):
        return self.title

class labels(models.Model):
    labelName = models.CharField(max_length=16)
    toBlog     = models.ForeignKey(to=blogs)
    def __str__(self):
        return self.labelName

class labelArticleRelationShip(models.Model):
    label    = models.ForeignKey(to=labels)
    article  = models.ForeignKey(to=articles)

    class Meta:
        unique_together = ("label", "article")

class readerAttitude(models.Model):
    reader  = models.ForeignKey(to=users)
    article = models.ForeignKey(to=articles)

    attitudeType = (
        (0, "favor"),
        (1, "oppose"),
    )
    attitude = models.IntegerField(choices=attitudeType)

    class Meta:
        unique_together = ("reader", "article")

class comments(models.Model):
    reader  = models.ForeignKey(to=users)
    article = models.ForeignKey(to=articles)
    content = models.CharField(max_length=128)
    ctime   = models.DateTimeField()
    parentComment = models.ForeignKey(to='self', to_field='id', related_name='back', null=True, blank=True)

    class Meta:
        ordering = ("-ctime",)

    def __str__(self):
        return  self.content

class troubleDetail(models.Model):
    detailContent = models.TextField()

class troubles(models.Model):
    title = models.CharField(max_length=64)
    summary = models.CharField(max_length=256)
    detail  = models.ForeignKey(to=troubleDetail)
    thePoser= models.ForeignKey(to=users, related_name='poser')
    ctime   = models.DateTimeField()

    markChoices = (
        (1, 'bad'),
        (2, 'common'),
        (3, 'good'),
    )
    mark  = models.IntegerField(choices=markChoices, null=True, blank=True)

    statusChoices = (
        (0, 'Have not processed'),
        (1, 'Processing'),
        (2, 'Processed'),
    )
    status = models.IntegerField(choices=statusChoices, default=0)

    theProcesser = models.ForeignKey(to=users, related_name='processer', null=True, blank=True)
    solution     = models.TextField(null=True, blank=True)
    ptime        = models.DateTimeField(null=True, blank=True)

class solutionAlternated(models.Model):
    title = models.CharField(max_length=64)
    content = models.TextField()

class Role(models.Model):
    caption = models.CharField(max_length=64)
    def __str__(self):
        return self.caption

class User2Role(models.Model):
    user = models.ForeignKey(to=users)
    role = models.ForeignKey(to=Role)
    def __str__(self):
        return '%s-%s'%(self.user.username, self.role.caption,)

class Action(models.Model):
    caption = models.CharField(max_length=64)
    code    = models.CharField(max_length=32)
    def __str__(self):
        return self.caption





class Menu(models.Model):
    caption = models.CharField(max_length=64)
    parentMenu = models.ForeignKey(to='self', related_name='p', null=True, blank=True)

class Permission(models.Model):
    caption = models.CharField(max_length=64)
    url     = models.CharField(max_length=256)
    menu    = models.ForeignKey(to=Menu, null=True, blank=True)
    def __str_(self):
        return '%s-%s'%(self.caption, self.url)

class Permission2Action(models.Model):
    permission = models.ForeignKey(to=Permission)
    action     = models.ForeignKey(to=Action)
    def __str__(self):
        return '%s-%s:%s/?t=%s'%(self.permission.caption, self.action.caption, self.permission.url, self.action.code)

class Permission2Action2Role(models.Model):
    p2a   = models.ForeignKey(to=Permission2Action)
    role  = models.ForeignKey(to=Role)
    def __str__(self):
        return '%s==>%s'%(self.role.caption, self.p2a)

mySite/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, HttpResponse
from django.utils.safestring import mark_safe
from django.urls import reverse

from repository import models
from utils import pagination

# Create your views here.


def index(request, *args, **kwargs):
    if kwargs:
        paginationHrefPrefix = reverse('mySiteIndex', kwargs=kwargs)
    else:
        paginationHrefPrefix = '/'

    siteArticles = models.articles.objects.filter(**kwargs)

    try:
        currentPageNum         = int(request.GET.get('currentPageNum'))
    except:
        currentPageNum         = 1

    paginations, startItemNum, endItemNum            = pagination.returnPaginations(currentPageNum, siteArticles.count(), paginationHrefPrefix)

    return render(request, "mySite/mySite_index.html", {'articleTypes':models.articles.type_choices, 'siteArticles': siteArticles[startItemNum:endItemNum], 'paginations':mark_safe(paginations)})

mySite/views/realViews.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, HttpResponse, redirect
from django.utils.safestring import mark_safe
from django.urls import reverse
from django.db.models import Q
import io

from repository import models
from utils import pagination, check_code, myForms


# Create your views here.


def index(request, *args, **kwargs):
    if kwargs:
        paginationHrefPrefix = reverse('mySiteIndex', kwargs=kwargs)
    else:
        paginationHrefPrefix = '/'
    siteArticles = models.articles.objects.filter(**kwargs)
    try:
        currentPageNum         = int(request.GET.get('currentPageNum'))
    except:
        currentPageNum         = 1
    paginations, startItemNum, endItemNum            = pagination.returnPaginations(currentPageNum, siteArticles.count(), paginationHrefPrefix)

    try:
        return render( request, "mySite/mySite_index.html", {'articleTypes': models.articles.type_choices,
                                                             'siteArticles': siteArticles[startItemNum:endItemNum],
                                                             'paginations': mark_safe( paginations ),
                                                             'surfix': models.blogs.objects.filter(owner_id=request.session['id_login']).first().surfix} )
    except:
        return render(request, "mySite/mySite_index.html", {'articleTypes':models.articles.type_choices, 'siteArticles': siteArticles[startItemNum:endItemNum], 'paginations':mark_safe(paginations)})


def doRegisterForm(request):
    if 'GET' == request.method:
        return render( request, "mySite/register.html", {'registerForm': myForms.registerForm()} )
    elif 'POST' == request.method:
        registerForm = myForms.registerForm(request.POST)
        if registerForm.is_valid():
            registerData = registerForm.clean()
            models.users.objects.create(username=registerData['username'], password=registerData['password'], email=registerData['email'], headPicture_path=registerData['headPicture_path'])
            return redirect('mySite/login.html')
        else:
            return render(request, "mySite/register.html", {'registerForm': registerForm})

def getValidateCodeImage(request):
    stream = io.BytesIO()
    img, code = check_code.create_validate_code()
    img.save(stream, "png")
    request.session["CheckCode"] = code
    return HttpResponse(stream.getvalue())

def doLogout(request):
    request.session.clear()
    return redirect('/')

def doLogin(request):
    if 'GET' == request.method:
        loginForm = myForms.loginForm()
        return render(request, 'mySite/login.html', {'loginForm':loginForm})
    elif 'POST' == request.method:
        loginForm = myForms.loginForm(request.POST)
        if loginForm.is_valid():
            if request.POST.get( 'checkCode' ).lower() == request.session['CheckCode'].lower():
                value_dict = loginForm.clean()
                con1 = Q()
                con1.children.append(Q(username=request.POST.get('username')) and Q(password=request.POST.get('password')))
                con2 = Q()
                con2.children.append(Q(email=request.POST.get('username')) and Q(password=request.POST.get('password')))
                loginUser = models.users.objects.filter(con1 or con2).first()
                if loginUser:
                    request.session['id_login'] = loginUser.id
                    request.session['username'] = loginUser.username

                    print(request.path_info)

                    role_list = models.Role.objects.filter(user2role__user=loginUser)
                    permission2action_list = models.Permission2Action.objects. \
                        filter( permission2action2role__role__in=role_list ). \
                        values( 'permission__url', 'action__code' ).distinct()


                    menu_leaf_list = list(models.Permission2Action.objects.\
                        filter(permission2action2role__role__in=role_list).exclude(permission__menu__isnull=True).\
                        values('permission_id','permission__url', 'permission__caption', 'permission__menu').distinct())



                    menu_list = list(models.Menu.objects.values('id', 'caption', 'parentMenu'))
                    
                    permission_action = {}
                    for content in permission2action_list:
                        if content['permission__url'] in permission_action:
                            permission_action[content['permission__url']].append( content['action__code'] )
                        else:
                            permission_action[content['permission__url']] = [content['action__code'], ]
                    request.session['permission_action_info'] = {
                        'menu_leaf_list': menu_leaf_list,
                        'menu_list'     : menu_list,
                        'permission_action' :permission_action
                    }




                    return redirect( '/' )
                else:
                    return render(request, 'mySite/login.html', {'loginForm': loginForm, 'loginError': 'username or password is Error'})

            else:
                return render( request, 'mySite/login.html',
                               {'loginForm': loginForm, 'loginError': 'CheckCode Error!'} )

templates/mySite/article.html
{% extends "./homeBase.html" %}
{% block js %}
    <script type="text/javascript" src="/font_statics/js/kindeditor-all.js" ></script>
{% endblock %}
{% block contentRight %}
    <p>{{ article.title }}</p>
    <p>{{ article.detail.content }}</p>
    <p>
        <button class="{% if 1 == favor %}theUserAttitude{% endif %}" id="favorButton"></button>
        <button class="{% if 1 == oppose %}theUserAttitude{% endif %}" id="opposeButton"></button>
    </p>
    <p id="commentsTrees" article="{{ article.id }}">
        {{ commentsTrees }}
    </p>
    <p><textarea id="commentToTheArticle"></textarea><button id="submitCommentOfTheArticle">提交</button></p>
    <script type="text/javascript" src="/font_statics/js/article.js"></script>
{% endblock %}

templates/mySite/home.html
{% extends "./homeBase.html" %}
{% block contentRight %}
    <div>
        {% for article in articles %}
            <div><a href='/{{ theBlog.surfix }}/{{ article.id }}.html'>{{ article.title }}</a></div>
            <div>{{ article.summary }}</div>
            <div class="articleDetails"><span>{{ article.ctime }}</span></div>
        {% endfor %}
    </div>
    {{ paginations }}
{% endblock %}

templates/mySite/homeBase.html
{% extends "base.html" %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="/font_statics/css/{{ theBlog.get_theme_display }}.css">
{% endblock %}
{% block body %}
    <div class="homeNavigator">
        <div class="blogNavigator">{{ theBlog.title }}</div>
        <div class="homeNavigatorDetails">
            <a href="/">首页</a>
            <a>个人首页</a>
            <a>管理</a>
        </div>
    </div>
    <div>
        <div class="homeContent">
            <div class="homeContentLeft">
                <div class="userNoticeArea">
                    <div class="notice">公告</div>
                    <div class="username">昵称：<span>{{ user.username }}</span></div>
                    <div>粉丝：</div>
                    <div>关注：</div>
                    <div>邮箱：{{ user.email }}</div>
                    <div class="ZhuangBi">{{ ZhuangBi }}</div>
                </div>
                <div class="labelArea">
                    <div>标签</div>
                    {% for label in labels %}
                        <div class="content"><a href="/{{ theBlog.surfix }}/label/{{ label.id }}.html">{{ label.labelName }}({{ label.count }})</a></div>
                    {% endfor %}
                </div>
                <div class="classficiationArea">
                    <div>分类</div>
                    {% for classficiation in theBlog.classifications_set.all %}
                        <div>{{ classficiation.className }}</div>
                    {% endfor %}
                </div>
                <div class="dateArea">
                    <div>时间</div>
                    {% for date in dates %}
                        <div><a href='/{{ theBlog.surfix }}/date/{{ date.theTime }}.html'>{{ date.theTime }}({{ date.theCount }})</a></div>
                    {% endfor %}
                </div>
            </div>
            <div class="homeContentRight">
                {% block contentRight %}
                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

templates/mySite/login.html
{% extends 'base.html' %}
{% block body %}
    {{ loginError }}
    <form method="post" action={% url 'login' %}>
    {% csrf_token %}
    {{ loginForm.username }}
    <div>{{ loginForm.username.errors.0 }}</div>
    {{ loginForm.password }}
    <div>{{ loginForm.password.errors.0 }}</div>
    <div>{{ loginForm.checkCode }}<img id="checkCodeImg" src="mySite/getCheckcode"></div>
    <input type="submit">
    </form>
    <script>
        $(document).ready(function () {
            $("#checkCodeImg").click(function () {
                $(this).attr("src", $(this).attr("src")+'?')
            })
        })
    </script>
{% endblock %}

templates/mySite/mySite_index.html
{% extends "base.html" %}

{% block head %}
    {% include "./navigation_header.html" %}
{% endblock %}

{% block body %}
    <div class="contentContainer">
        <div class="leftContent">
            {% for article in siteArticles %}
                <div class="element">
                    <div class="articleTitle">{{ article.title }}</div>
                    <img src="{{ article.ownerBlog.owner.headPicture_path }}">
                    <p class="articleSummary">{{ article.summary }}</p>
                    <div class="elementOthers">
                        <img src="/font_statics/images/personImage.png" class="contentVerticalMiddle"><span class="contentVerticalMiddle authorName">{{ article.ownerBlog.owner.username }}</span>
                        <span class="contentVerticalMiddle ctimeLabel">发布于</span><span class="contentVerticalMiddle ctime">{{ article.ctime.year }}-{{ article.ctime.month }}-{{ article.ctime.day }}</span>
                        <span class="contentVerticalMiddle comments"></span>
                        {% if article.favorCount %}
                            <span class="contentVerticalMiddle favorRelated">
                                {{ article.favorCount }}
                            </span>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="rightContent"></div>
    </div>
    <div class="paginations">{{ paginations }}</div>
{% endblock %}

templates/mySite/navigation_header.html
<div class="navigation_header">
    <div class="content">
        <span>老子的技术论坛</span>
        <a href='/'>全部</a>
        {% for type in articleTypes %}
            <a href={% url "mySiteIndex" articleType=type.0 %}>{{ type.1 }}</a>
        {% endfor %}
        <span class="userArea">
            {% if request.session.username %}
                <a href='/{{ surfix }}.html'>{{ request.session.username }}</a>
                <span>.</span>
                <a href="" class="myBlog">我的博客</a>
                <span>.</span>
                <a>管理</a>|<a href='{% url 'logout' %}'>退出</a>
            {% else %}
                <a href={% url 'register' %}>注册</a>|<a href={% url 'login' %}>登录</a>
            {% endif %}
        </span>
    </div>
</div>

templates/mySite/register.html
{% extends 'base.html' %}
{% block css %}
    <link type="text/css" rel="stylesheet" href="/font_statics/css/register.css">
{% endblock %}
{% block jquery %}
{% endblock %}
{% block body %}
        {{ registerForm.non_field_errors }}
        <div class="registerFormTitle">注册</div>
        <form method="post" action={% url 'register' %} class="registerForm">
        {% csrf_token %}
        {{ registerForm.username }}
        <div>{{ registerForm.errors.username.0 }}</div>
        {{ registerForm.email }}
        <div>{{ registerForm.errors.email.0 }}</div>
        {{ registerForm.password }}
        <div>{{ registerForm.errors.password.0 }}</div>
        {{ registerForm.confirmPassword }}
        <div>{{ registerForm.errors.confirmPassword.0 }}</div>
        {{ registerForm.checkCode }}
        <div>{{ registerForm.errors.checkCode.0 }}</div>
        {{ registerForm.headPicture_path }}
        <input type="submit">
    </form>
{% endblock %}